# Generated by Django 3.2.25 on 2024-08-14 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_management_app', '0003_auto_20240810_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
